TYPE_DEFAULT_TASKER = "Default_Template"
TYPE_EXTRA_TASKER = "Extra_Template"
TYPE_DEFAULT_METHOD = "Default_Template"
TYPE_EXTRA_METHOD = "Extra_Template"
TYPE_DEFAULT_CLASS_FUNC = "Default_Template"
TYPE_EXTRA_CLASS_FUNC = "Extra_Template"
CONDITION_SUCCESS = True # 正常运行
CONDITION_FAIL = False # 程序报错
BLOCK_LIST = ["||||", "\t"]
EXIT = "exit"