# 初始化变量
main_container_list = []
class_func_list = []
df_container_template_list = []
ex_container_template_list = []
io_list = []
message_list = []
method_list = []
df_task_template_list = []
ex_task_template_list = []